default_stages:
- commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: mixed-line-ending
    - id: check-case-conflict

- repo: https://github.com/python-poetry/poetry
  rev: 1.5.1
  hooks:
    - id: poetry-check
      args: ["-C", "./backend"]
      name: poetry check
      verbose: true

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    exclude: tests/|alembic/
    additional_dependencies:
      - 'pydantic'


- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.278
  hooks:
    - id: ruff

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]
