version: "3.9"
services:
#  backend:
#    container_name: sl-backend
#    build:
#      context: backend
#      dockerfile: backend/Dockerfile
#    ports:
#      - "8000:8000"
#    depends_on:
#      - database
#  frontend:
#    container_name: sl-frontend
#    build:
#      context: frontend
#      dockerfile: frontend/Dockerfile
#    ports:
#      - "3000:3000"
  database:
    image: postgres
    container_name: sl-shopping-list
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    healthcheck:
      test: [ 'CMD-SHELL', "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
