[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Matt Barkway <matt.barkway@ovo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.98.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
