name: Build and Push Docker
description: yes

inputs:
  ecr_repository_url:
    description: 'ECR repository URL'
    required: true
  aws_access_key_id:
    description: 'The AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'The AWS secret access key'
    required: true
  aws_region:
    description: 'The AWS region'
    required: true
  container_name:
    description: 'Name of the container'
    required: true
  ec2_instance_name:
    description: 'Name of the EC2 instance'
    required: true
  ports:
    description: 'Port mapping for the docker run command'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Run deployment script on EC2 instance
      shell: bash
      run: |
        command_id=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=${{ inputs.ec2_instance_name }}" \
          --parameters '{"commands":["docker stop ${{ inputs.container_name }} || true", "docker rm ${{ inputs.container_name }} || true", "docker pull ${{ inputs.ecr_repository_url }}:latest", "docker run -d -p 80:80 --name ${{ inputs.container_name }} ${{ inputs.ecr_repository_url }}:latest"]}' \
          --query "Command.CommandId" \
          --output text \
          --region ${{ inputs.aws_region }})

        status=$(aws ssm list-command-invocations \
          --command-id "$command_id" \
          --query "CommandInvocations[0].Status" \
          --output text \
          --region ${{ inputs.aws_region }})

        if [[ "$status" == "Success" ]]; then
          echo "::set-output name=result::success"
        else
          echo "::set-output name=result::failure"
          exit 1
        fi
