"""index username

Revision ID: 30b5bf3147f9
Revises: 353ac7208a4e
Create Date: 2024-02-12 12:22:26.352745

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "30b5bf3147f9"
down_revision = "353ac7208a4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
