"""add updated and created at

Revision ID: 5e0e2dbc5470
Revises: 7ad9da91426f
Create Date: 2024-01-29 15:20:44.063167

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e0e2dbc5470"
down_revision = "7ad9da91426f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collaborator", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "collaborator", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("item", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("item", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column(
        "shopping_list", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "shopping_list", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("shopping_list", "updated_at")
    op.drop_column("shopping_list", "created_at")
    op.drop_column("item", "updated_at")
    op.drop_column("item", "created_at")
    op.drop_column("collaborator", "updated_at")
    op.drop_column("collaborator", "created_at")
    # ### end Alembic commands ###
