service_name = "sl"
db_username = "admin123"
db_password ="vertopsupersecretnoguessplease1no*"
frontend_task_definition_path = "frontend-task-definition.json"
backend_task_definition_path = "backend-task-definition.json"
name = "sl"
