name: main

on:
  push:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/filters.yaml

      - name: Build Python
        uses: ./.github/actions/builder
        with:
          working-directory: 'backend'

      - name: Check python
        if: always() && (steps.changes.outputs.python == 'true' || steps.changes.outputs.interpreter == 'true')
        uses: ./.github/actions/check-python
        with:
          working-directory: 'backend'

      - name: Check JS
        if: always() && steps.changes.outputs.js == 'true'
        uses: ./.github/actions/check-js
        with:
          working-directory: 'frontend'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/filters.yaml

      - name: Build Python
        uses: ./.github/actions/builder
        with:
          working-directory: 'backend'

      - name: Test python
        if: always() && (steps.changes.outputs.python == 'true' || steps.changes.outputs.interpreter == 'true')
        uses: ./.github/actions/test-python
        with:
          working-directory: 'backend'
          path: 'tests/'

      - name: Test JS
        if: always() && steps.changes.outputs.js == 'true'
        uses: ./.github/actions/test-js
        with:
          working-directory: 'frontend'
          path: '.'


  build-and-publish:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/filters.yaml

      - name: Deploy backend
        if: always() && steps.changes.outputs.backend == 'true'
        uses: ./.github/actions/fly-deploy
        with:
          fly-token: ${{ secrets.FLY_TOKEN }}
          working-directory: backend

      - name: Deploy frontend
        if: always() && steps.changes.outputs.frontend == 'true'
        uses: ./.github/actions/fly-deploy
        with:
          fly-token: ${{ secrets.FLY_TOKEN }}
          working-directory: frontend
